// Generated by Bisonc++ V4.09.02 on Fri, 09 Dec 2016 18:17:54 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {290, 8}, // 1: start (INT) ->  INT MAIN OPEN CLOSE LBRACE declarations instructions RBRACE
     {291, 0}, // 2: declarations ->  <empty>
     {291, 2}, // 3: declarations ->  declaration declarations
     {293, 3}, // 4: declaration (UNSIGNED) ->  UNSIGNED VARIABLE SEMICOLON
     {293, 3}, // 5: declaration (BOOL) ->  BOOL VARIABLE SEMICOLON
     {292, 1}, // 6: instructions ->  instruction
     {292, 2}, // 7: instructions ->  instruction instructions
     {294, 1}, // 8: instruction ->  assign
     {294, 1}, // 9: instruction ->  in
     {294, 1}, // 10: instruction ->  out
     {294, 1}, // 11: instruction ->  branching
     {294, 1}, // 12: instruction ->  cycle
     {295, 4}, // 13: assign (VARIABLE) ->  VARIABLE ASSIGNMENT expression SEMICOLON
     {296, 4}, // 14: in (CIN) ->  CIN READ VARIABLE SEMICOLON
     {297, 4}, // 15: out (COUT) ->  COUT WRITE expression SEMICOLON
     {298, 7}, // 16: branching (IF) ->  IF OPEN expression CLOSE LBRACE instructions RBRACE
     {298, 11}, // 17: branching (IF) ->  IF OPEN expression CLOSE LBRACE instructions RBRACE ELSE LBRACE instructions RBRACE
     {299, 7}, // 18: cycle (WHILE) ->  WHILE OPEN expression CLOSE LBRACE instructions RBRACE
     {300, 1}, // 19: expression (NUMBER) ->  NUMBER
     {300, 1}, // 20: expression (TRUE) ->  TRUE
     {300, 1}, // 21: expression (FALSE) ->  FALSE
     {300, 1}, // 22: expression (VARIABLE) ->  VARIABLE
     {300, 3}, // 23: expression (AND) ->  expression AND expression
     {300, 3}, // 24: expression (OR) ->  expression OR expression
     {300, 2}, // 25: expression (NOT) ->  NOT expression
     {300, 3}, // 26: expression (EQUAL) ->  expression EQUAL expression
     {300, 3}, // 27: expression (SMALLER) ->  expression SMALLER expression
     {300, 3}, // 28: expression (BIGGER) ->  expression BIGGER expression
     {300, 3}, // 29: expression (PLUS) ->  expression PLUS expression
     {300, 3}, // 30: expression (MINUS) ->  expression MINUS expression
     {300, 3}, // 31: expression (MULTIPLY) ->  expression MULTIPLY expression
     {300, 3}, // 32: expression (DIV) ->  expression DIV expression
     {300, 3}, // 33: expression (MOD) ->  expression MOD expression
     {300, 3}, // 34: expression (OPEN) ->  OPEN expression CLOSE
     {301, 1}, // 35: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 3} },         
    { {       290}, { 1} }, // start
    { {       259}, { 2} }, // INT  
    { {         0}, { 0} },         
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 2} },        
    { {       260}, { 3} }, // MAIN
    { {         0}, { 0} },        
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 2} },        
    { {       270}, { 4} }, // OPEN
    { {         0}, { 0} },        
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, { 2} },         
    { {       271}, { 5} }, // CLOSE
    { {         0}, { 0} },         
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, { 2} },          
    { {       257}, { 6} }, // LBRACE
    { {         0}, { 0} },          
};

SR__ s_6[] =
{
    { { REQ_DEF}, {  5} },                
    { {     291}, {  7} }, // declarations
    { {     293}, {  8} }, // declaration 
    { {     261}, {  9} }, // UNSIGNED    
    { {     262}, { 10} }, // BOOL        
    { {       0}, { -2} },                
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, { 13} },                
    { {       292}, { 11} }, // instructions
    { {       294}, { 12} }, // instruction 
    { {       295}, { 13} }, // assign      
    { {       296}, { 14} }, // in          
    { {       297}, { 15} }, // out         
    { {       298}, { 16} }, // branching   
    { {       299}, { 17} }, // cycle       
    { {       277}, { 18} }, // VARIABLE    
    { {       269}, { 19} }, // CIN         
    { {       268}, { 20} }, // COUT        
    { {       265}, { 21} }, // IF          
    { {       267}, { 22} }, // WHILE       
    { {         0}, {  0} },                
};

SR__ s_8[] =
{
    { { REQ_DEF}, {  5} },                
    { {     291}, { 23} }, // declarations
    { {     293}, {  8} }, // declaration 
    { {     261}, {  9} }, // UNSIGNED    
    { {     262}, { 10} }, // BOOL        
    { {       0}, { -2} },                
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       277}, { 24} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       277}, { 25} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       258}, { 26} }, // RBRACE
    { {         0}, {  0} },          
};

SR__ s_12[] =
{
    { { REQ_DEF}, { 13} },                
    { {     292}, { 27} }, // instructions
    { {     294}, { 12} }, // instruction 
    { {     295}, { 13} }, // assign      
    { {     296}, { 14} }, // in          
    { {     297}, { 15} }, // out         
    { {     298}, { 16} }, // branching   
    { {     299}, { 17} }, // cycle       
    { {     277}, { 18} }, // VARIABLE    
    { {     269}, { 19} }, // CIN         
    { {     268}, { 20} }, // COUT        
    { {     265}, { 21} }, // IF          
    { {     267}, { 22} }, // WHILE       
    { {       0}, { -6} },                
};

SR__ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       274}, { 28} }, // ASSIGNMENT
    { {         0}, {  0} },              
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       273}, { 29} }, // READ
    { {         0}, {  0} },        
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       272}, { 30} }, // WRITE
    { {         0}, {  0} },         
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       270}, { 31} }, // OPEN
    { {         0}, {  0} },        
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       270}, { 32} }, // OPEN
    { {         0}, {  0} },        
};

SR__ s_23[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       275}, { 33} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       275}, { 34} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_26[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 35} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       277}, { 42} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 43} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 44} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 45} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_33[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 12} },             
    { {       275}, { 46} }, // SEMICOLON
    { {       279}, { 47} }, // AND      
    { {       280}, { 48} }, // OR       
    { {       282}, { 49} }, // EQUAL    
    { {       283}, { 50} }, // SMALLER  
    { {       284}, { 51} }, // BIGGER   
    { {       285}, { 52} }, // PLUS     
    { {       286}, { 53} }, // MINUS    
    { {       287}, { 54} }, // MULTIPLY 
    { {       288}, { 55} }, // DIV      
    { {       289}, { 56} }, // MOD      
    { {         0}, {  0} },             
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 57} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 58} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       275}, { 59} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, { 12} },             
    { {       275}, { 60} }, // SEMICOLON
    { {       279}, { 47} }, // AND      
    { {       280}, { 48} }, // OR       
    { {       282}, { 49} }, // EQUAL    
    { {       283}, { 50} }, // SMALLER  
    { {       284}, { 51} }, // BIGGER   
    { {       285}, { 52} }, // PLUS     
    { {       286}, { 53} }, // MINUS    
    { {       287}, { 54} }, // MULTIPLY 
    { {       288}, { 55} }, // DIV      
    { {       289}, { 56} }, // MOD      
    { {         0}, {  0} },             
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 12} },            
    { {       271}, { 61} }, // CLOSE   
    { {       279}, { 47} }, // AND     
    { {       280}, { 48} }, // OR      
    { {       282}, { 49} }, // EQUAL   
    { {       283}, { 50} }, // SMALLER 
    { {       284}, { 51} }, // BIGGER  
    { {       285}, { 52} }, // PLUS    
    { {       286}, { 53} }, // MINUS   
    { {       287}, { 54} }, // MULTIPLY
    { {       288}, { 55} }, // DIV     
    { {       289}, { 56} }, // MOD     
    { {         0}, {  0} },            
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 12} },            
    { {       271}, { 62} }, // CLOSE   
    { {       279}, { 47} }, // AND     
    { {       280}, { 48} }, // OR      
    { {       282}, { 49} }, // EQUAL   
    { {       283}, { 50} }, // SMALLER 
    { {       284}, { 51} }, // BIGGER  
    { {       285}, { 52} }, // PLUS    
    { {       286}, { 53} }, // MINUS   
    { {       287}, { 54} }, // MULTIPLY
    { {       288}, { 55} }, // DIV     
    { {       289}, { 56} }, // MOD     
    { {         0}, {  0} },            
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 63} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 64} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 65} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 66} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 67} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 68} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 69} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 70} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 71} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       300}, { 72} }, // expression
    { {       276}, { 36} }, // NUMBER    
    { {       263}, { 37} }, // TRUE      
    { {       264}, { 38} }, // FALSE     
    { {       277}, { 39} }, // VARIABLE  
    { {       281}, { 40} }, // NOT       
    { {       270}, { 41} }, // OPEN      
    { {         0}, {  0} },              
};

SR__ s_57[] =
{
    { { REQ_DEF}, {   9} },            
    { {     282}, {  49} }, // EQUAL   
    { {     283}, {  50} }, // SMALLER 
    { {     284}, {  51} }, // BIGGER  
    { {     285}, {  52} }, // PLUS    
    { {     286}, {  53} }, // MINUS   
    { {     287}, {  54} }, // MULTIPLY
    { {     288}, {  55} }, // DIV     
    { {     289}, {  56} }, // MOD     
    { {       0}, { -25} },            
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, { 12} },            
    { {       271}, { 73} }, // CLOSE   
    { {       279}, { 47} }, // AND     
    { {       280}, { 48} }, // OR      
    { {       282}, { 49} }, // EQUAL   
    { {       283}, { 50} }, // SMALLER 
    { {       284}, { 51} }, // BIGGER  
    { {       285}, { 52} }, // PLUS    
    { {       286}, { 53} }, // MINUS   
    { {       287}, { 54} }, // MULTIPLY
    { {       288}, { 55} }, // DIV     
    { {       289}, { 56} }, // MOD     
    { {         0}, {  0} },            
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       257}, { 74} }, // LBRACE
    { {         0}, {  0} },          
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       257}, { 75} }, // LBRACE
    { {         0}, {  0} },          
};

SR__ s_63[] =
{
    { { REQ_DEF}, {  10} },            
    { {     280}, {  48} }, // OR      
    { {     282}, {  49} }, // EQUAL   
    { {     283}, {  50} }, // SMALLER 
    { {     284}, {  51} }, // BIGGER  
    { {     285}, {  52} }, // PLUS    
    { {     286}, {  53} }, // MINUS   
    { {     287}, {  54} }, // MULTIPLY
    { {     288}, {  55} }, // DIV     
    { {     289}, {  56} }, // MOD     
    { {       0}, { -23} },            
};

SR__ s_64[] =
{
    { { REQ_DEF}, {   9} },            
    { {     282}, {  49} }, // EQUAL   
    { {     283}, {  50} }, // SMALLER 
    { {     284}, {  51} }, // BIGGER  
    { {     285}, {  52} }, // PLUS    
    { {     286}, {  53} }, // MINUS   
    { {     287}, {  54} }, // MULTIPLY
    { {     288}, {  55} }, // DIV     
    { {     289}, {  56} }, // MOD     
    { {       0}, { -24} },            
};

SR__ s_65[] =
{
    { { REQ_DEF}, {   8} },            
    { {     283}, {  50} }, // SMALLER 
    { {     284}, {  51} }, // BIGGER  
    { {     285}, {  52} }, // PLUS    
    { {     286}, {  53} }, // MINUS   
    { {     287}, {  54} }, // MULTIPLY
    { {     288}, {  55} }, // DIV     
    { {     289}, {  56} }, // MOD     
    { {       0}, { -26} },            
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   6} },            
    { {     285}, {  52} }, // PLUS    
    { {     286}, {  53} }, // MINUS   
    { {     287}, {  54} }, // MULTIPLY
    { {     288}, {  55} }, // DIV     
    { {     289}, {  56} }, // MOD     
    { {       0}, { -27} },            
};

SR__ s_67[] =
{
    { { REQ_DEF}, {   6} },            
    { {     285}, {  52} }, // PLUS    
    { {     286}, {  53} }, // MINUS   
    { {     287}, {  54} }, // MULTIPLY
    { {     288}, {  55} }, // DIV     
    { {     289}, {  56} }, // MOD     
    { {       0}, { -28} },            
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   4} },            
    { {     287}, {  54} }, // MULTIPLY
    { {     288}, {  55} }, // DIV     
    { {     289}, {  56} }, // MOD     
    { {       0}, { -29} },            
};

SR__ s_69[] =
{
    { { REQ_DEF}, {   4} },            
    { {     287}, {  54} }, // MULTIPLY
    { {     288}, {  55} }, // DIV     
    { {     289}, {  56} }, // MOD     
    { {       0}, { -30} },            
};

SR__ s_70[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_71[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_72[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, { 13} },                
    { {       292}, { 76} }, // instructions
    { {       294}, { 12} }, // instruction 
    { {       295}, { 13} }, // assign      
    { {       296}, { 14} }, // in          
    { {       297}, { 15} }, // out         
    { {       298}, { 16} }, // branching   
    { {       299}, { 17} }, // cycle       
    { {       277}, { 18} }, // VARIABLE    
    { {       269}, { 19} }, // CIN         
    { {       268}, { 20} }, // COUT        
    { {       265}, { 21} }, // IF          
    { {       267}, { 22} }, // WHILE       
    { {         0}, {  0} },                
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, { 13} },                
    { {       292}, { 77} }, // instructions
    { {       294}, { 12} }, // instruction 
    { {       295}, { 13} }, // assign      
    { {       296}, { 14} }, // in          
    { {       297}, { 15} }, // out         
    { {       298}, { 16} }, // branching   
    { {       299}, { 17} }, // cycle       
    { {       277}, { 18} }, // VARIABLE    
    { {       269}, { 19} }, // CIN         
    { {       268}, { 20} }, // COUT        
    { {       265}, { 21} }, // IF          
    { {       267}, { 22} }, // WHILE       
    { {         0}, {  0} },                
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       258}, { 78} }, // RBRACE
    { {         0}, {  0} },          
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       258}, { 79} }, // RBRACE
    { {         0}, {  0} },          
};

SR__ s_78[] =
{
    { { REQ_DEF}, {   2} },        
    { {     266}, {  80} }, // ELSE
    { {       0}, { -16} },        
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       257}, { 81} }, // LBRACE
    { {         0}, {  0} },          
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, { 13} },                
    { {       292}, { 82} }, // instructions
    { {       294}, { 12} }, // instruction 
    { {       295}, { 13} }, // assign      
    { {       296}, { 14} }, // in          
    { {       297}, { 15} }, // out         
    { {       298}, { 16} }, // branching   
    { {       299}, { 17} }, // cycle       
    { {       277}, { 18} }, // VARIABLE    
    { {       269}, { 19} }, // CIN         
    { {       268}, { 20} }, // COUT        
    { {       265}, { 21} }, // IF          
    { {       267}, { 22} }, // WHILE       
    { {         0}, {  0} },                
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       258}, { 83} }, // RBRACE
    { {         0}, {  0} },          
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 4:
#line 56 "cpp.y"
        {
         if (symbolTable.count(*d_vsp__[-1].name) > 0)
         {
         std::stringstream ss;
         ss << "Ujradeklaralt valtozo: " << *d_vsp__[-1].name << "." << std::endl
         << "Korabbi deklaracio sora: " << symbolTable[*d_vsp__[-1].name].decl_row << std::endl;
         error (ss.str().c_str());
         } else
         {
         symbolTable[*d_vsp__[-1].name] = var_data (d_loc__.first_line, number);
         }
         }
        break;

        case 5:
#line 70 "cpp.y"
        {
         if (symbolTable.count(*d_vsp__[-1].name) > 0)
         {
         std::stringstream ss;
         ss << "Ujradeklaralt valtozo: " << *d_vsp__[-1].name << "." << std::endl
         << "Korabbi deklaracio sora: " << symbolTable[*d_vsp__[-1].name].decl_row << std::endl;
         error (ss.str().c_str());
         } else
         {
         symbolTable[*d_vsp__[-1].name] = var_data (d_loc__.first_line, boolean);
         }
         }
        break;

        case 13:
#line 104 "cpp.y"
        {
         if (symbolTable.count(*d_vsp__[-3].name) < 1)
         {
         std::stringstream ss;
         ss << "Nem deklaralt valtozo: " << *d_vsp__[-3].name << "." << std::endl;
         error (ss.str().c_str());
         }
         else if (symbolTable[*d_vsp__[-3].name].var_type != *d_vsp__[-1].var_type)
         {
         error( "Tipushibas ertekadas.\n" );
         }
         delete d_vsp__[-3].name;
         delete d_vsp__[-1].var_type;
         }
        break;

        case 14:
#line 122 "cpp.y"
        {
         if (symbolTable.count(*d_vsp__[-1].name) < 1)
         {
         std::stringstream ss;
         ss << "Nem deklaralt valtozo: " << *d_vsp__[-1].name << "." << std::endl;
         error (ss.str().c_str());
         }
         delete d_vsp__[-1].name;
         }
        break;

        case 16:
#line 139 "cpp.y"
        {
         if (*d_vsp__[-4].var_type != boolean)
         {
         std::stringstream ss;
         ss << "Nem logikai kifejezes: " << *d_vsp__[-4].var_type << "." << std::endl;
         error (ss.str().c_str());
         }
         delete d_vsp__[-4].var_type;
         }
        break;

        case 17:
#line 150 "cpp.y"
        {
         if (*d_vsp__[-8].var_type != boolean)
         {
         std::stringstream ss;
         ss << "Nem logikai kifejezes: " << *d_vsp__[-8].var_type << "." << std::endl;
         error (ss.str().c_str());
         }
         delete d_vsp__[-8].var_type;
         }
        break;

        case 18:
#line 163 "cpp.y"
        {
         if (*d_vsp__[-4].var_type != boolean)
         {
         std::stringstream ss;
         ss << "Nem logikai kifejezes: " << *d_vsp__[-4].var_type << "." << std::endl;
         error (ss.str().c_str());
         }
         delete d_vsp__[-4].var_type;
         }
        break;

        case 19:
#line 176 "cpp.y"
        {
         d_val__.var_type = new type(number);
         }
        break;

        case 20:
#line 181 "cpp.y"
        {
         d_val__.var_type = new type(boolean);
         }
        break;

        case 21:
#line 186 "cpp.y"
        {
         d_val__.var_type = new type(boolean);
         }
        break;

        case 22:
#line 191 "cpp.y"
        {
         if (symbolTable.count(*d_vsp__[0].name) > 0)
         {
         d_val__.var_type = new type(symbolTable[*d_vsp__[0].name].var_type);
         } else
         {
         std::stringstream ss;
         ss << "Nem deklaralt valtozo: " << *d_vsp__[0].name << "." << std::endl;
         error (ss.str().c_str());
         }
         }
        break;

        case 23:
#line 204 "cpp.y"
        {
         if ((*d_vsp__[-2].var_type == *d_vsp__[0].var_type) && *d_vsp__[0].var_type == boolean)
         {
         d_val__.var_type = new type(boolean);
         } else
         {
         error( "Csak logikai kifejezeseket lehet osszeeselni!\n" );
         }
         delete d_vsp__[-2].var_type;
         delete d_vsp__[0].var_type;
         }
        break;

        case 24:
#line 217 "cpp.y"
        {
         if ((*d_vsp__[-2].var_type == *d_vsp__[0].var_type) && *d_vsp__[0].var_type == boolean)
         {
         d_val__.var_type = new type(boolean);
         } else
         {
         error( "Csak logikai kifejezeseket lehet osszevagyolni!\n" );
         }
         delete d_vsp__[-2].var_type;
         delete d_vsp__[0].var_type;
         }
        break;

        case 25:
#line 230 "cpp.y"
        {
         if (*d_vsp__[0].var_type == boolean)
         {
         d_val__.var_type = new type(boolean);
         }
         else
         {
         std::stringstream ss;
         ss << "Nem logikai kifejezes: " << *d_vsp__[0].var_type << "." << std::endl;
         error (ss.str().c_str());
         }
         delete d_vsp__[0].var_type;
         }
        break;

        case 26:
#line 245 "cpp.y"
        {
         if (*d_vsp__[-2].var_type == *d_vsp__[0].var_type)
         {
         d_val__.var_type = new type(boolean);
         } else
         {
         error( "Csak azonos tipusu kifejezeseket lehet osszehasonlitani!\n" );
         }
         delete d_vsp__[-2].var_type;
         delete d_vsp__[0].var_type;
         }
        break;

        case 27:
#line 258 "cpp.y"
        {
         if ((*d_vsp__[-2].var_type == *d_vsp__[0].var_type) && *d_vsp__[0].var_type == number)
         {
         d_val__.var_type = new type(boolean);
         } else
         {
         error( "Csak szamokat lehet osszehasonlitani!\n" );
         }
         delete d_vsp__[-2].var_type;
         delete d_vsp__[0].var_type;
         }
        break;

        case 28:
#line 271 "cpp.y"
        {
         if ((*d_vsp__[-2].var_type == *d_vsp__[0].var_type) && *d_vsp__[0].var_type == number)
         {
         d_val__.var_type = new type(boolean);
         } else
         {
         error( "Csak szamokat lehet osszehasonlitani!\n" );
         }
         delete d_vsp__[-2].var_type;
         delete d_vsp__[0].var_type;
         }
        break;

        case 29:
#line 284 "cpp.y"
        {
         if ((*d_vsp__[-2].var_type == *d_vsp__[0].var_type) && *d_vsp__[0].var_type == number)
         {
         d_val__.var_type = new type(number);
         } else
         {
         error( "Csak szamokat lehet osszeadni!\n" );
         }
         delete d_vsp__[-2].var_type;
         delete d_vsp__[0].var_type;
         }
        break;

        case 30:
#line 297 "cpp.y"
        {
         if ((*d_vsp__[-2].var_type == *d_vsp__[0].var_type) && *d_vsp__[0].var_type == number)
         {
         d_val__.var_type = new type(number);
         } else
         {
         error( "Csak szamokat lehet kivonni!\n" );
         }
         delete d_vsp__[-2].var_type;
         delete d_vsp__[0].var_type;
         }
        break;

        case 31:
#line 310 "cpp.y"
        {
         if ((*d_vsp__[-2].var_type == *d_vsp__[0].var_type) && *d_vsp__[0].var_type == number)
         {
         d_val__.var_type = new type(number);
         } else
         {
         error( "Csak szamokat lehet szorozni!\n" );
         }
         delete d_vsp__[-2].var_type;
         delete d_vsp__[0].var_type;
         }
        break;

        case 32:
#line 323 "cpp.y"
        {
         if ((*d_vsp__[-2].var_type == *d_vsp__[0].var_type) && *d_vsp__[0].var_type == number)
         {
         d_val__.var_type = new type(number);
         } else
         {
         error( "Csak szamokat lehet osztani!\n" );
         }
         delete d_vsp__[-2].var_type;
         delete d_vsp__[0].var_type;
         }
        break;

        case 33:
#line 336 "cpp.y"
        {
         if ((*d_vsp__[-2].var_type == *d_vsp__[0].var_type) && *d_vsp__[0].var_type == number)
         {
         d_val__.var_type = new type(number);
         } else
         {
         error( "Csak szamokat lehet maradekosan osztani!\n" );
         }
         delete d_vsp__[-2].var_type;
         delete d_vsp__[0].var_type;
         }
        break;

        case 34:
#line 349 "cpp.y"
        {
         d_val__.var_type = new type(*d_vsp__[-1].var_type);
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



