// Generated by Bisonc++ V4.09.02 on Wed, 11 Jan 2017 13:44:16 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {299, 8}, // 1: start (INT) ->  INT MAIN BALZAROJEL JOBBZAROJEL KEZDES deklaraciok utasitasok VEGE
     {300, 0}, // 2: deklaraciok ->  <empty>
     {300, 2}, // 3: deklaraciok ->  deklaracio deklaraciok
     {302, 3}, // 4: deklaracio (EGESZ) ->  EGESZ AZONOSITO PONTOSVESSZO
     {302, 3}, // 5: deklaracio (LOGIKAI) ->  LOGIKAI AZONOSITO PONTOSVESSZO
     {302, 3}, // 6: deklaracio (FIXPONTOS) ->  FIXPONTOS AZONOSITO PONTOSVESSZO
     {301, 1}, // 7: utasitasok ->  utasitas
     {301, 2}, // 8: utasitasok ->  utasitas utasitasok
     {303, 1}, // 9: utasitas ->  ertekadas
     {303, 1}, // 10: utasitas ->  be
     {303, 1}, // 11: utasitas ->  ki
     {303, 1}, // 12: utasitas ->  elagazas
     {303, 1}, // 13: utasitas ->  ciklus
     {304, 4}, // 14: ertekadas (AZONOSITO) ->  AZONOSITO ERTEKADAS kifejezes PONTOSVESSZO
     {305, 4}, // 15: be (BEMENET) ->  BEMENET OLVAS AZONOSITO PONTOSVESSZO
     {306, 4}, // 16: ki (KIMENET) ->  KIMENET IR kifejezes PONTOSVESSZO
     {307, 7}, // 17: elagazas (HA) ->  HA BALZAROJEL kifejezes JOBBZAROJEL KEZDES utasitasok VEGE
     {307, 11}, // 18: elagazas (HA) ->  HA BALZAROJEL kifejezes JOBBZAROJEL KEZDES utasitasok VEGE KULONBEN KEZDES utasitasok VEGE
     {308, 7}, // 19: ciklus (AMIG) ->  AMIG BALZAROJEL kifejezes JOBBZAROJEL KEZDES utasitasok VEGE
     {309, 1}, // 20: kifejezes (FIXPONTOSSZAM) ->  FIXPONTOSSZAM
     {309, 1}, // 21: kifejezes (SZAM) ->  SZAM
     {309, 1}, // 22: kifejezes (IGAZ) ->  IGAZ
     {309, 1}, // 23: kifejezes (HAMIS) ->  HAMIS
     {309, 1}, // 24: kifejezes (AZONOSITO) ->  AZONOSITO
     {309, 4}, // 25: kifejezes (EGESZRESZ) ->  EGESZRESZ BALZAROJEL kifejezes JOBBZAROJEL
     {309, 4}, // 26: kifejezes (TORTRESZ) ->  TORTRESZ BALZAROJEL kifejezes JOBBZAROJEL
     {309, 3}, // 27: kifejezes (PLUSZ) ->  kifejezes PLUSZ kifejezes
     {309, 3}, // 28: kifejezes (MINUSZ) ->  kifejezes MINUSZ kifejezes
     {309, 3}, // 29: kifejezes (SZORZAS) ->  kifejezes SZORZAS kifejezes
     {309, 3}, // 30: kifejezes (OSZTAS) ->  kifejezes OSZTAS kifejezes
     {309, 3}, // 31: kifejezes (MARADEK) ->  kifejezes MARADEK kifejezes
     {309, 3}, // 32: kifejezes (KISEBB) ->  kifejezes KISEBB kifejezes
     {309, 3}, // 33: kifejezes (NAGYOBB) ->  kifejezes NAGYOBB kifejezes
     {309, 3}, // 34: kifejezes (EGYENLO) ->  kifejezes EGYENLO kifejezes
     {309, 3}, // 35: kifejezes (ES) ->  kifejezes ES kifejezes
     {309, 3}, // 36: kifejezes (VAGY) ->  kifejezes VAGY kifejezes
     {309, 2}, // 37: kifejezes (NEM) ->  NEM kifejezes
     {309, 3}, // 38: kifejezes (BALZAROJEL) ->  BALZAROJEL kifejezes JOBBZAROJEL
     {310, 1}, // 39: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 3} },         
    { {       299}, { 1} }, // start
    { {       257}, { 2} }, // INT  
    { {         0}, { 0} },         
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 2} },        
    { {       258}, { 3} }, // MAIN
    { {         0}, { 0} },        
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 2} },              
    { {       275}, { 4} }, // BALZAROJEL
    { {         0}, { 0} },              
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, { 2} },               
    { {       276}, { 5} }, // JOBBZAROJEL
    { {         0}, { 0} },               
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, { 2} },          
    { {       259}, { 6} }, // KEZDES
    { {         0}, { 0} },          
};

SR__ s_6[] =
{
    { { REQ_DEF}, {  6} },               
    { {     300}, {  7} }, // deklaraciok
    { {     302}, {  8} }, // deklaracio 
    { {     261}, {  9} }, // EGESZ      
    { {     262}, { 10} }, // LOGIKAI    
    { {     263}, { 11} }, // FIXPONTOS  
    { {       0}, { -2} },               
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, { 13} },              
    { {       301}, { 12} }, // utasitasok
    { {       303}, { 13} }, // utasitas  
    { {       304}, { 14} }, // ertekadas 
    { {       305}, { 15} }, // be        
    { {       306}, { 16} }, // ki        
    { {       307}, { 17} }, // elagazas  
    { {       308}, { 18} }, // ciklus    
    { {       281}, { 19} }, // AZONOSITO 
    { {       272}, { 20} }, // BEMENET   
    { {       271}, { 21} }, // KIMENET   
    { {       264}, { 22} }, // HA        
    { {       266}, { 23} }, // AMIG      
    { {         0}, {  0} },              
};

SR__ s_8[] =
{
    { { REQ_DEF}, {  6} },               
    { {     300}, { 24} }, // deklaraciok
    { {     302}, {  8} }, // deklaracio 
    { {     261}, {  9} }, // EGESZ      
    { {     262}, { 10} }, // LOGIKAI    
    { {     263}, { 11} }, // FIXPONTOS  
    { {       0}, { -2} },               
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 25} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 26} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 27} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 28} }, // VEGE
    { {         0}, {  0} },        
};

SR__ s_13[] =
{
    { { REQ_DEF}, { 13} },              
    { {     301}, { 29} }, // utasitasok
    { {     303}, { 13} }, // utasitas  
    { {     304}, { 14} }, // ertekadas 
    { {     305}, { 15} }, // be        
    { {     306}, { 16} }, // ki        
    { {     307}, { 17} }, // elagazas  
    { {     308}, { 18} }, // ciklus    
    { {     281}, { 19} }, // AZONOSITO 
    { {     272}, { 20} }, // BEMENET   
    { {     271}, { 21} }, // KIMENET   
    { {     264}, { 22} }, // HA        
    { {     266}, { 23} }, // AMIG      
    { {       0}, { -7} },              
};

SR__ s_14[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       274}, { 30} }, // ERTEKADAS
    { {         0}, {  0} },             
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       267}, { 31} }, // OLVAS
    { {         0}, {  0} },         
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       268}, { 32} }, // IR
    { {         0}, {  0} },      
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       275}, { 33} }, // BALZAROJEL
    { {         0}, {  0} },              
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       275}, { 34} }, // BALZAROJEL
    { {         0}, {  0} },              
};

SR__ s_24[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       273}, { 35} }, // PONTOSVESSZO
    { {         0}, {  0} },                
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       273}, { 36} }, // PONTOSVESSZO
    { {         0}, {  0} },                
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       273}, { 37} }, // PONTOSVESSZO
    { {         0}, {  0} },                
};

SR__ s_28[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_29[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 38} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 48} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 49} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 50} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 51} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_35[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       273}, { 52} }, // PONTOSVESSZO
    { {       288}, { 53} }, // PLUSZ       
    { {       289}, { 54} }, // MINUSZ      
    { {       290}, { 55} }, // SZORZAS     
    { {       291}, { 56} }, // OSZTAS      
    { {       292}, { 57} }, // MARADEK     
    { {       286}, { 58} }, // KISEBB      
    { {       287}, { 59} }, // NAGYOBB     
    { {       285}, { 60} }, // EGYENLO     
    { {       283}, { 61} }, // ES          
    { {       282}, { 62} }, // VAGY        
    { {         0}, {  0} },                
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       275}, { 63} }, // BALZAROJEL
    { {         0}, {  0} },              
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       275}, { 64} }, // BALZAROJEL
    { {         0}, {  0} },              
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 65} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 66} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       273}, { 67} }, // PONTOSVESSZO
    { {         0}, {  0} },                
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       273}, { 68} }, // PONTOSVESSZO
    { {       288}, { 53} }, // PLUSZ       
    { {       289}, { 54} }, // MINUSZ      
    { {       290}, { 55} }, // SZORZAS     
    { {       291}, { 56} }, // OSZTAS      
    { {       292}, { 57} }, // MARADEK     
    { {       286}, { 58} }, // KISEBB      
    { {       287}, { 59} }, // NAGYOBB     
    { {       285}, { 60} }, // EGYENLO     
    { {       283}, { 61} }, // ES          
    { {       282}, { 62} }, // VAGY        
    { {         0}, {  0} },                
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, { 12} },               
    { {       276}, { 69} }, // JOBBZAROJEL
    { {       288}, { 53} }, // PLUSZ      
    { {       289}, { 54} }, // MINUSZ     
    { {       290}, { 55} }, // SZORZAS    
    { {       291}, { 56} }, // OSZTAS     
    { {       292}, { 57} }, // MARADEK    
    { {       286}, { 58} }, // KISEBB     
    { {       287}, { 59} }, // NAGYOBB    
    { {       285}, { 60} }, // EGYENLO    
    { {       283}, { 61} }, // ES         
    { {       282}, { 62} }, // VAGY       
    { {         0}, {  0} },               
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, { 12} },               
    { {       276}, { 70} }, // JOBBZAROJEL
    { {       288}, { 53} }, // PLUSZ      
    { {       289}, { 54} }, // MINUSZ     
    { {       290}, { 55} }, // SZORZAS    
    { {       291}, { 56} }, // OSZTAS     
    { {       292}, { 57} }, // MARADEK    
    { {       286}, { 58} }, // KISEBB     
    { {       287}, { 59} }, // NAGYOBB    
    { {       285}, { 60} }, // EGYENLO    
    { {       283}, { 61} }, // ES         
    { {       282}, { 62} }, // VAGY       
    { {         0}, {  0} },               
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 71} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 72} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 73} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 74} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 75} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 76} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 77} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 78} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 79} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 80} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 81} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, { 11} },                 
    { {       309}, { 82} }, // kifejezes    
    { {       278}, { 39} }, // FIXPONTOSSZAM
    { {       277}, { 40} }, // SZAM         
    { {       279}, { 41} }, // IGAZ         
    { {       280}, { 42} }, // HAMIS        
    { {       281}, { 43} }, // AZONOSITO    
    { {       269}, { 44} }, // EGESZRESZ    
    { {       270}, { 45} }, // TORTRESZ     
    { {       284}, { 46} }, // NEM          
    { {       275}, { 47} }, // BALZAROJEL   
    { {         0}, {  0} },                 
};

SR__ s_65[] =
{
    { { REQ_DEF}, {   9} },           
    { {     288}, {  53} }, // PLUSZ  
    { {     289}, {  54} }, // MINUSZ 
    { {     290}, {  55} }, // SZORZAS
    { {     291}, {  56} }, // OSZTAS 
    { {     292}, {  57} }, // MARADEK
    { {     286}, {  58} }, // KISEBB 
    { {     287}, {  59} }, // NAGYOBB
    { {     285}, {  60} }, // EGYENLO
    { {       0}, { -37} },           
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, { 12} },               
    { {       276}, { 83} }, // JOBBZAROJEL
    { {       288}, { 53} }, // PLUSZ      
    { {       289}, { 54} }, // MINUSZ     
    { {       290}, { 55} }, // SZORZAS    
    { {       291}, { 56} }, // OSZTAS     
    { {       292}, { 57} }, // MARADEK    
    { {       286}, { 58} }, // KISEBB     
    { {       287}, { 59} }, // NAGYOBB    
    { {       285}, { 60} }, // EGYENLO    
    { {       283}, { 61} }, // ES         
    { {       282}, { 62} }, // VAGY       
    { {         0}, {  0} },               
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       259}, { 84} }, // KEZDES
    { {         0}, {  0} },          
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       259}, { 85} }, // KEZDES
    { {         0}, {  0} },          
};

SR__ s_71[] =
{
    { { REQ_DEF}, {   4} },           
    { {     290}, {  55} }, // SZORZAS
    { {     291}, {  56} }, // OSZTAS 
    { {     292}, {  57} }, // MARADEK
    { {       0}, { -27} },           
};

SR__ s_72[] =
{
    { { REQ_DEF}, {   4} },           
    { {     290}, {  55} }, // SZORZAS
    { {     291}, {  56} }, // OSZTAS 
    { {     292}, {  57} }, // MARADEK
    { {       0}, { -28} },           
};

SR__ s_73[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_74[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_75[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_76[] =
{
    { { REQ_DEF}, {   6} },           
    { {     288}, {  53} }, // PLUSZ  
    { {     289}, {  54} }, // MINUSZ 
    { {     290}, {  55} }, // SZORZAS
    { {     291}, {  56} }, // OSZTAS 
    { {     292}, {  57} }, // MARADEK
    { {       0}, { -32} },           
};

SR__ s_77[] =
{
    { { REQ_DEF}, {   6} },           
    { {     288}, {  53} }, // PLUSZ  
    { {     289}, {  54} }, // MINUSZ 
    { {     290}, {  55} }, // SZORZAS
    { {     291}, {  56} }, // OSZTAS 
    { {     292}, {  57} }, // MARADEK
    { {       0}, { -33} },           
};

SR__ s_78[] =
{
    { { REQ_DEF}, {   8} },           
    { {     288}, {  53} }, // PLUSZ  
    { {     289}, {  54} }, // MINUSZ 
    { {     290}, {  55} }, // SZORZAS
    { {     291}, {  56} }, // OSZTAS 
    { {     292}, {  57} }, // MARADEK
    { {     286}, {  58} }, // KISEBB 
    { {     287}, {  59} }, // NAGYOBB
    { {       0}, { -34} },           
};

SR__ s_79[] =
{
    { { REQ_DEF}, {   9} },           
    { {     288}, {  53} }, // PLUSZ  
    { {     289}, {  54} }, // MINUSZ 
    { {     290}, {  55} }, // SZORZAS
    { {     291}, {  56} }, // OSZTAS 
    { {     292}, {  57} }, // MARADEK
    { {     286}, {  58} }, // KISEBB 
    { {     287}, {  59} }, // NAGYOBB
    { {     285}, {  60} }, // EGYENLO
    { {       0}, { -35} },           
};

SR__ s_80[] =
{
    { { REQ_DEF}, {  10} },           
    { {     288}, {  53} }, // PLUSZ  
    { {     289}, {  54} }, // MINUSZ 
    { {     290}, {  55} }, // SZORZAS
    { {     291}, {  56} }, // OSZTAS 
    { {     292}, {  57} }, // MARADEK
    { {     286}, {  58} }, // KISEBB 
    { {     287}, {  59} }, // NAGYOBB
    { {     285}, {  60} }, // EGYENLO
    { {     283}, {  61} }, // ES     
    { {       0}, { -36} },           
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, { 12} },               
    { {       276}, { 86} }, // JOBBZAROJEL
    { {       288}, { 53} }, // PLUSZ      
    { {       289}, { 54} }, // MINUSZ     
    { {       290}, { 55} }, // SZORZAS    
    { {       291}, { 56} }, // OSZTAS     
    { {       292}, { 57} }, // MARADEK    
    { {       286}, { 58} }, // KISEBB     
    { {       287}, { 59} }, // NAGYOBB    
    { {       285}, { 60} }, // EGYENLO    
    { {       283}, { 61} }, // ES         
    { {       282}, { 62} }, // VAGY       
    { {         0}, {  0} },               
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, { 12} },               
    { {       276}, { 87} }, // JOBBZAROJEL
    { {       288}, { 53} }, // PLUSZ      
    { {       289}, { 54} }, // MINUSZ     
    { {       290}, { 55} }, // SZORZAS    
    { {       291}, { 56} }, // OSZTAS     
    { {       292}, { 57} }, // MARADEK    
    { {       286}, { 58} }, // KISEBB     
    { {       287}, { 59} }, // NAGYOBB    
    { {       285}, { 60} }, // EGYENLO    
    { {       283}, { 61} }, // ES         
    { {       282}, { 62} }, // VAGY       
    { {         0}, {  0} },               
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, { 13} },              
    { {       301}, { 88} }, // utasitasok
    { {       303}, { 13} }, // utasitas  
    { {       304}, { 14} }, // ertekadas 
    { {       305}, { 15} }, // be        
    { {       306}, { 16} }, // ki        
    { {       307}, { 17} }, // elagazas  
    { {       308}, { 18} }, // ciklus    
    { {       281}, { 19} }, // AZONOSITO 
    { {       272}, { 20} }, // BEMENET   
    { {       271}, { 21} }, // KIMENET   
    { {       264}, { 22} }, // HA        
    { {       266}, { 23} }, // AMIG      
    { {         0}, {  0} },              
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, { 13} },              
    { {       301}, { 89} }, // utasitasok
    { {       303}, { 13} }, // utasitas  
    { {       304}, { 14} }, // ertekadas 
    { {       305}, { 15} }, // be        
    { {       306}, { 16} }, // ki        
    { {       307}, { 17} }, // elagazas  
    { {       308}, { 18} }, // ciklus    
    { {       281}, { 19} }, // AZONOSITO 
    { {       272}, { 20} }, // BEMENET   
    { {       271}, { 21} }, // KIMENET   
    { {       264}, { 22} }, // HA        
    { {       266}, { 23} }, // AMIG      
    { {         0}, {  0} },              
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 90} }, // VEGE
    { {         0}, {  0} },        
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 91} }, // VEGE
    { {         0}, {  0} },        
};

SR__ s_90[] =
{
    { { REQ_DEF}, {   2} },            
    { {     265}, {  92} }, // KULONBEN
    { {       0}, { -17} },            
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       259}, { 93} }, // KEZDES
    { {         0}, {  0} },          
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, { 13} },              
    { {       301}, { 94} }, // utasitasok
    { {       303}, { 13} }, // utasitas  
    { {       304}, { 14} }, // ertekadas 
    { {       305}, { 15} }, // be        
    { {       306}, { 16} }, // ki        
    { {       307}, { 17} }, // elagazas  
    { {       308}, { 18} }, // ciklus    
    { {       281}, { 19} }, // AZONOSITO 
    { {       272}, { 20} }, // BEMENET   
    { {       271}, { 21} }, // KIMENET   
    { {       264}, { 22} }, // HA        
    { {       266}, { 23} }, // AMIG      
    { {         0}, {  0} },              
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       260}, { 95} }, // VEGE
    { {         0}, {  0} },        
};

SR__ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 57 "cpp.y"
        {
         }
        break;

        case 2:
#line 63 "cpp.y"
        {
         }
        break;

        case 3:
#line 67 "cpp.y"
        {
         }
        break;

        case 4:
#line 73 "cpp.y"
        {
         if( szimb_tabla.count(*d_vsp__[-1].szoveg) > 0 )
         {
         std::cerr << d_loc__.first_line << ".: A(z) '" << *d_vsp__[-1].szoveg << "' valtozo mar definialva volt a "
         << szimb_tabla[*d_vsp__[-1].szoveg].def_sora << ". sorban." << std::endl;
         exit(1);
         }
         else
         {
         szimb_tabla[*d_vsp__[-1].szoveg] = valtozo_leiro(d_loc__.first_line,Egesz);
         }
         delete d_vsp__[-1].szoveg;
         }
        break;

        case 5:
#line 88 "cpp.y"
        {
         if( szimb_tabla.count(*d_vsp__[-1].szoveg) > 0 )
         {
         std::cerr << d_loc__.first_line << ".: A(z) '" << *d_vsp__[-1].szoveg << "' valtozo mar definialva volt a "
         << szimb_tabla[*d_vsp__[-1].szoveg].def_sora << ". sorban." << std::endl;
         exit(1);
         }
         else
         {
         szimb_tabla[*d_vsp__[-1].szoveg] = valtozo_leiro(d_loc__.first_line,Logikai);
         }
         delete d_vsp__[-1].szoveg;
         }
        break;

        case 6:
#line 103 "cpp.y"
        {
         if( szimb_tabla.count(*d_vsp__[-1].szoveg) > 0 )
         {
         std::cerr << d_loc__.first_line << ".: A(z) '" << *d_vsp__[-1].szoveg << "' valtozo mar definialva volt a "
         << szimb_tabla[*d_vsp__[-1].szoveg].def_sora << ". sorban." << std::endl;
         exit(1);
         }
         else
         {
         szimb_tabla[*d_vsp__[-1].szoveg] = valtozo_leiro(d_loc__.first_line, Fixpontos);
         }
         delete d_vsp__[-1].szoveg;
         }
        break;

        case 7:
#line 120 "cpp.y"
        {
         }
        break;

        case 8:
#line 124 "cpp.y"
        {
         }
        break;

        case 9:
#line 130 "cpp.y"
        {
         }
        break;

        case 10:
#line 134 "cpp.y"
        {
         }
        break;

        case 11:
#line 138 "cpp.y"
        {
         }
        break;

        case 12:
#line 142 "cpp.y"
        {
         }
        break;

        case 13:
#line 146 "cpp.y"
        {
         }
        break;

        case 14:
#line 152 "cpp.y"
        {
         if( szimb_tabla.count( *d_vsp__[-3].szoveg ) == 0 )
         {
         std::cerr << d_loc__.first_line << ": A(z) '" << *d_vsp__[-3].szoveg << "' valtozo nincs deklaralva." << std::endl;
         exit(1);
         }
         else if( szimb_tabla[*d_vsp__[-3].szoveg].vtip != d_vsp__[-1].kif->ktip )
         {
         std::cerr << d_loc__.first_line << ": Az ertekadas jobb- es baloldalan kulonbozo tipusu kifejezesek allnak." << std::endl;
         exit(1);
         }
         else
         {
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line );
         }
         delete d_vsp__[-1].kif;
         }
        break;

        case 15:
#line 173 "cpp.y"
        {
         if( szimb_tabla.count( *d_vsp__[-1].szoveg ) == 0 )
         {
         std::cerr << d_loc__.first_line << ": A(z) '" << *d_vsp__[-1].szoveg << "' valtozo nincs deklaralva." << std::endl;
         exit(1);
         }
         else
         {
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line );
         }
         delete d_vsp__[-1].szoveg;
         }
        break;

        case 16:
#line 189 "cpp.y"
        {
         d_val__.utasitas = new utasitas_leiro( d_loc__.first_line );
         delete d_vsp__[-1].kif;
         }
        break;

        case 17:
#line 197 "cpp.y"
        {
         if( d_vsp__[-4].kif->ktip != Logikai )
         {
         std::cerr << d_loc__.first_line << ": Nem logikai tipusu az elagazas feltetele." << std::endl;
         exit(1);
         }
         else
         {
         d_val__.utasitas = new utasitas_leiro( d_vsp__[-4].kif->sor );
         }
         delete d_vsp__[-4].kif;
         }
        break;

        case 18:
#line 211 "cpp.y"
        {
         if( d_vsp__[-8].kif->ktip != Logikai )
         {
         std::cerr << d_loc__.first_line << ": Nem logikai tipusu az elagazas feltetele." << std::endl;
         exit(1);
         }
         else
         {
         d_val__.utasitas = new utasitas_leiro( d_vsp__[-8].kif->sor );
         }
         delete d_vsp__[-8].kif;
         }
        break;

        case 19:
#line 227 "cpp.y"
        {
         if( d_vsp__[-4].kif->ktip != Logikai )
         {
         std::cerr << d_loc__.first_line << ": Nem logikai tipusu a ciklus feltetele." << std::endl;
         exit(1);
         }
         else
         {
         d_val__.utasitas = new utasitas_leiro( d_vsp__[-4].kif->sor );
         }
         delete d_vsp__[-4].kif;
         }
        break;

        case 20:
#line 243 "cpp.y"
        {
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Fixpontos );
         delete d_vsp__[0].szoveg;
         }
        break;

        case 21:
#line 249 "cpp.y"
        {
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz );
         delete d_vsp__[0].szoveg;
         }
        break;

        case 22:
#line 255 "cpp.y"
        {
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         }
        break;

        case 23:
#line 260 "cpp.y"
        {
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         }
        break;

        case 24:
#line 265 "cpp.y"
        {
         if( szimb_tabla.count( *d_vsp__[0].szoveg ) == 0 )
         {
         std::cerr << d_loc__.first_line << ": A(z) '" << *d_vsp__[0].szoveg << "' valtozo nincs deklaralva." << std::endl;
         exit(1);
         }
         else
         {
         valtozo_leiro vl = szimb_tabla[*d_vsp__[0].szoveg];
         d_val__.kif = new kifejezes_leiro( vl.def_sora, vl.vtip );
         delete d_vsp__[0].szoveg;
         }
         }
        break;

        case 25:
#line 280 "cpp.y"
        {
         if( d_vsp__[-1].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[-1].kif->sor << ": A 'fixpart' operator nem fixpontos tipusu kifejezesbol all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz );
         delete d_vsp__[-1].kif;
         }
        break;

        case 26:
#line 291 "cpp.y"
        {
         if( d_vsp__[-1].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[-1].kif->sor << ": A 'fraction' operator nem fixpontos tipusu kifejezesbol all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz );
         delete d_vsp__[-1].kif;
         }
        break;

        case 27:
#line 302 "cpp.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz && d_vsp__[-2].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A '+' operator baloldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz && d_vsp__[0].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '+' operator jobboldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[-2].kif->ktip != d_vsp__[0].kif->ktip )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '+' operator ket oldalan nem azonos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, d_vsp__[-2].kif->ktip );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 28:
#line 324 "cpp.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz && d_vsp__[-2].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A '-' operator baloldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz && d_vsp__[0].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '-' operator jobboldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[-2].kif->ktip != d_vsp__[0].kif->ktip )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '-' operator ket oldalan nem azonos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, d_vsp__[-2].kif->ktip );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 29:
#line 346 "cpp.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz && d_vsp__[-2].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A '*' operator baloldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz && d_vsp__[0].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '*' operator jobboldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[-2].kif->ktip != d_vsp__[0].kif->ktip )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '*' operator ket oldalan nem azonos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, d_vsp__[-2].kif->ktip );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 30:
#line 368 "cpp.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz && d_vsp__[-2].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A 'div' operator baloldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz && d_vsp__[0].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A 'div' operator jobboldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[-2].kif->ktip != d_vsp__[0].kif->ktip )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A 'div' operator ket oldalan nem azonos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, d_vsp__[-2].kif->ktip );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 31:
#line 390 "cpp.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz && d_vsp__[-2].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A 'mod' operator baloldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz && d_vsp__[0].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A 'mod' operator jobboldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[-2].kif->ktip != d_vsp__[0].kif->ktip )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A 'mod' operator ket oldalan nem azonos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, d_vsp__[-2].kif->ktip );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 32:
#line 412 "cpp.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz && d_vsp__[-2].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A '<' operator baloldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz && d_vsp__[0].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '<' operator jobboldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[-2].kif->ktip != d_vsp__[0].kif->ktip )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '<' operator ket oldalan nem azonos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 33:
#line 434 "cpp.y"
        {
         if( d_vsp__[-2].kif->ktip != Egesz && d_vsp__[-2].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": A '>' operator baloldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz && d_vsp__[0].kif->ktip != Fixpontos )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '>' operator jobboldalan nem egesz vagy fixpontos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[-2].kif->ktip != d_vsp__[0].kif->ktip )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A '>' operator ket oldalan nem azonos tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 34:
#line 456 "cpp.y"
        {
         if( d_vsp__[-2].kif->ktip != d_vsp__[0].kif->ktip )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": Az '=' operator jobb- es baloldalan kulonbozo tipusu kifejezesek allnak." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 35:
#line 468 "cpp.y"
        {
         if( d_vsp__[-2].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": Az 'and' operator baloldalan nem logikai tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[0].kif->sor << ": Az 'and' operator jobboldalan nem logikai tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 36:
#line 485 "cpp.y"
        {
         if( d_vsp__[-2].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": Az 'or' operator baloldalan nem logikai tipusu kifejezes all." << std::endl;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[0].kif->sor << ": Az 'or' operator jobboldalan nem logikai tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 37:
#line 502 "cpp.y"
        {
         if( d_vsp__[0].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[0].kif->sor << ": A 'NEM' operator utan nem logikai tipusu kifejezes all." << std::endl;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         delete d_vsp__[0].kif;
         }
        break;

        case 38:
#line 513 "cpp.y"
        {
         d_val__.kif = d_vsp__[-1].kif;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



